### ISSUE TITLE
Some unit tests failed locally in VS Code

### ISSUE THREAD

**Issue by ychen1492** [acroucher/PyTOUGH#41] opened 2022-12-29 19:19 UTC
Hi, thanks for sharing the code. I am trying to check some methods using unit tests. I see the github action build is fine, however, I get some failed unit tests locally in vscode. It seems like the paths to the test data are not set properly. All test data is in the subfolders of `tests`. After I made the following adjustments, 
![image](https://user-images.githubusercontent.com/46110208/209998000-ad7790a0-ebfa-49cd-8e7f-831f52f1a942.png)
I can debug the unit tests in vscode.
![image](https://user-images.githubusercontent.com/46110208/209998998-dd527ef4-12f6-469d-b167-7e9ae3749a8a.png)
I am using the master version of this tool, Commit hash: 1e205948fe2e267ba32c2a83f1cb601e0689c8c9
I see in github actions, you are using the ubuntu Linux rather than the windows machine. I am not sure if this results in the success in github actions but failed on my local machine. 

Another issue I have is on the integer data type, it looks like numpy doesn't have `int` type, instead, only `int` works fine. I am not sure if anyone else has an issue there.
![image](https://user-images.githubusercontent.com/46110208/210000646-454242d5-e4ed-4859-a672-108ac9ff223c.png)

Thanks again.

**Comment by acroucher** [comment] 2023-01-16 01:33
I am not sure what caused the issue with the unit test data path, maybe VSCode tries to run them from the top directory of the PyTOUGH install? If you look at the script used to run the unit tests as a Github Action (`.github/workflows/pythontest.yml`) you will see it navigates to the `tests` directory first before running the tests.

> Another issue I have is on the integer data type

This is caused by recent changes to numpy and is fixed in the PyTOUGH testing branch - will be in the next release of PyTOUGH.

**Closed** 2024-09-11 04:54 UTC
