### ISSUE TITLE
lst.write_vtk error

### ISSUE THREAD

**Issue by wyangattud** [acroucher/PyTOUGH#16] opened 2018-04-09 08:35 UTC
When I try to use lst.write_vtk to generate the vtk files, it gives me the following info：
AttributeError: 'vtkCommonCorePython.vtkCharArray' object has no attribute 'SetTupleValue'.
Does anyone also meet this error?

**Comment by acroucher** [comment] 2018-04-10 02:44
Which version of VTK are you using? A few people running recent versions of VTK have reported problems like this- it looks like VTK may have made some changes that are not backwards-compatible. I am running VTK 6.3 here and it is working OK.

**Comment by labgeothermal** [comment] 2018-04-21 02:37
I am using python 2.7.14, pytough 1.5.0 and vtk 6.3.0, but still got an error when running 'Hydrostatic 3D Model' in Pytough example, as follow:
Traceback (most recent call last):
  File "tiga.py", line 51, in <module>
    dat.grid.write_vtk(geo, 'INFILE.vtu')
  File "C:\Python27\lib\site-packages\t2grids.py", line 551, in write_vtk
    vtu = geo.get_vtk_grid(arrays, surface_snap)
  File "C:\Python27\lib\site-packages\mulgrids.py", line 3166, in get_vtk_grid
    node3d, elt3d = self.grid3d(surface_snap)
  File "C:\Python27\lib\site-packages\mulgrids.py", line 3085, in grid3d
    unique_elevations, columns = unique_values(col_surf, surface_snap)
  File "C:\Python27\lib\site-packages\mulgrids.py", line 3074, in unique_values
    uniques = asort[d > tol]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1.

**Comment by acroucher** [comment] 2018-04-22 03:30
Yes, I think that is a separate issue, and one that has been recently fixed in the PyTOUGH testing branch:
https://github.com/acroucher/PyTOUGH/commit/786d8559ce155be45a52bff1609243d74d90b628

Can you try pulling the latest testing branch and see if it fixes your problem?

**Comment by labgeothermal** [comment] 2018-04-23 04:03
Yes, it fixes my problem.
Thank you very much.

**Comment by acroucher** [comment] 2018-05-24 01:57
I think this problem is now fixed by commit cba5177df703365448c643daaacb62851d38502c. It was caused by some changes made in VTK 7.1 (the vtkCharArray SetTupleValues() method was changed to SetTypedTuple()). So the PyTOUGH VTK export should now work for VTK 7.1 and later.

**Closed by acroucher** 2018-05-24 01:57 UTC
